### ISSUE TITLE
Support ARM

### ISSUE THREAD

**Issue by TomHart** [WyriHaximus/github-action-helm3#44]
Is it possible to make this support ARM runners? When I try this action I get the error:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /workdir/entrypoint.sh: exec format error
```

**Comment by WyriHaximus** [comment]
Hey @TomHart, have you tried the master branch? Need to finalize some reworking in there, but that does support `arm64` and `arm`. (If `arm` doesn't work there let me know because I'm only using it on `arm64` personally these days.)

**Comment by WyriHaximus** [comment]
Hey @TomHart released v3 earlier today that works on `arm64` runners. (Have my own raspberry pi kubernetes cluster I'm using them on.)
