### ISSUE TITLE
Replace deprecated set-output command

### ISSUE THREAD

**Issue by BjoernPetersen** [WyriHaximus/github-action-helm3#45]
The `save-state` and `set-output` commands  have been deprecated, so this action's usage of `set-output` should be replaced. See this blog post: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/WyriHaximus/github-action-helm3/blob/240b28c59f85ac58ed1e19314a97f09eaf9cbffb/main.js#L98

**Comment by WyriHaximus** [comment]
It's on my list to update all my actions. But thanks for pointing me to the blog and docs on this 👍

**Comment by Jorehn** [comment]
This issue is already solved in master, can we expect a new release any time soon?

**Comment by WyriHaximus** [comment]
@Jorehn `v3` has been released today.
