### ISSUE TITLE
unable to find version `v3`

### ISSUE THREAD

**Issue by akshaydwarakanath1** [WyriHaximus/github-action-helm3#61]
when using `WyriHaximus/github-action-helm3@v3` i'm getting the following error.

`Error: Unable to resolve action WyriHaximus/github-action-helm3@v3, unable to find version v3`

Previously was using `WyriHaximus/github-action-helm3@master`.

**Comment by WyriHaximus** [comment]
Correct, prepared the documentation already for the v3 release. Will post an update here as well when `v3` is out.

**Comment by WyriHaximus** [comment]
`v3` is about available through [`v3.0.0`](https://github.com/WyriHaximus/github-action-helm3/releases/tag/v3.0.0)
