### ISSUE TITLE
Action's cache dirs are stored in working directory

### ISSUE THREAD

**Issue by BjoernPetersen** [WyriHaximus/github-action-helm3#63]
When using the `v3` version of this action, I ran into an issue because the action stores its cache dirs `docker-kube-config-[...]` and `helm-cache-[...]` in the working directory. That will lead to an error 413 (Request Entity Too Large) when trying to install the chart in the working directory.

Anyone else affected reading this: add these lines to your `.helmignore` (create one if it doesn't exist) to work around this issue:

```
helm-cache-*/
docker-kube-config-*/
```

**Comment by WyriHaximus** [comment]
Oof good point, I'll update https://github.com/WyriHaximus/github-action-helm3/blob/45bd8731554a60e6b4151d334b94c7de88b7c8cf/main.js#L18-L23 to use the system tmp location.

**Comment by WyriHaximus** [comment]
`v3.0.1` is out to fix this. Also found some other minor things to improve, but this one was causing issues, thank you for reporting :+1:
