### ISSUE TITLE
v2 uses set-output which will be deprecated soon

### ISSUE THREAD

**Issue by lucetre** [WyriHaximus/github-action-helm3#67]
We wanted to try to upgrade our action to **v3** to avoid the issue. But it fails to apply with the updated default release name (`RELEASE-NAME` to `release-name` since newer helm forces lowercase)

> [Setup, Build, and Deploy]
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Could you guys fix the **v2** action to follow `GITHUB_OUTPUT` as [the official guideline](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)?

It would be super helpful for us without renaming release name of the deployed resources (https://engineering.salesforce.com/how-to-rename-a-helm-release-6fdcd7526ac7/). Thanks 🙏

**Comment by WyriHaximus** [comment]
Hey @lucetre, I'll finish some maintenance on the v2 branch and then release a new tag. I might have also updated Helm in that branch, but would have to check for you.

**Comment by WyriHaximus** [comment]
@lucetre What is the version that caused issues for you? I've bumped the 2.x branch to 3.11 a while ago: https://github.com/WyriHaximus/github-action-helm3/pull/60

**Comment by lucetre** [comment]
Thanks @WyriHaximus for caring this. We have resolved the issue by the below step.
```
 - name: Set up helm
    uses: azure/setup-helm@v3
    with:
      version: 'v3.0.1'
```
