### ISSUE TITLE
Node16 is deprecated, need to update

### ISSUE THREAD

**Issue by corneliusroemer** [WyriHaximus/github-action-helm3#77]
I got the following warning:
>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: WyriHaximus/github-action-helm3@v3

Can you update node to 20 and make a new major release? That'd be great!

**Comment by WyriHaximus** [comment]
@corneliusroemer Thanks fot the PR. Why the new major tho? (Purely out of interest since I've seen that pattern in recent weeks.)

**Comment by WyriHaximus** [comment]
P.S. Will hold off releasing until @corneliusroemer responds because I feel there is something I'm missing.

**Comment by corneliusroemer** [comment]
That's a good question! I suppose users like to be able to opt in to changes in node version but I don't know why. I'm not an actions author myself.

I suppose if nothing but the node version changes there's no need to bump major version. This also means no one needs to update their workflows.

**Comment by WyriHaximus** [comment]
> That's a good question! I suppose users like to be able to opt in to changes in node version but I don't know why. I'm not an actions author myself.

As an action author this is the first time I've ran into this as well. Also this is the first time we've seen a major nodejs version bump wave going across the platform.

> I suppose if nothing but the node version changes there's no need to bump major version. This also means no one needs to update their workflows.

At this point I've purely using this action from self hosted runners myself. And with those you often have to install nodejs and provide the version you want. So I get why we see purely the nodejs version bump as the reason to do a major new version. On GitHub's hosted runners this isn't an issue tho. So I'll go ahead and tag a new major version tomorrow.

**Comment by WyriHaximus** [comment]
Just released v4: https://github.com/WyriHaximus/github-action-helm3/releases/tag/v4.0.0
